### ISSUE TITLE
Make this package standalone

### ISSUE THREAD

**Issue by voronianski** [reapp/reapp-ui#46]
This will be huge.. components should not be dependant on `reapp`. My case - I want to use `Gallery` component in regular react app that I already have -

``` javascript
import Gallery from 'reapp-ui/components/Gallery';
```

throws an error:

``` bash
/node_modules/reapp-ui/components/Gallery.jsx:8
var { Scroller } = require('reapp-scroller');
    ^
SyntaxError: Unexpected token {
```

**Comment by natew** [comment]
Ah, this is only because reapp is using ES6 syntax so as of now it needs to be transpiled. I'd like for it to be set up so it's compiled before releasing to npm, but it's a relatively big task.

You can use it independently though today absolutely, just use babel to transpile it in your app (via Webpack or Browserify). I'll update here once I get it working without transpile though.

**Comment by voronianski** [comment]
@natew I'm using babel but I'm not transpiling node_modules.

**Comment by natew** [comment]
Yea reapp-UI needs to be transpired. For now you could do something like
reapp-pack does where it excludes other packages besides reapp-UI.

**Comment by natew** [comment]
It is now transpiled!

**Comment by yornaath** [comment]
I dont think it is enough to just use `babel` here because of `.css` files being required. I think you have to run `cssify` on the `.css` files and replace them with the generated js files in the `/build` directory. As per #58
