### ISSUE TITLE
Icon syntax doesn't match docs

### ISSUE THREAD

**Issue by mbrookes** [reapp/reapp-ui#48]
In the documentation, `<Icon />` takes a name (presumably without the svg suffix?), and an optional path. In the current implementation, it looks like it takes a file with a relative path and svg extension, which appears to need to be wrapped with a require:

Current (based on the HN app implementation):

```
<Icon file={require('reapp-kit/icons/check.svg')} size='38px' color='#FFFFFF' />
```

I'm guessing from the documentation the intention for `name=` was:

```
<Icon name='check' size='38px' color='#FFFFFF' />
```

(With an optional `path=` to locate non-standard icons.)

In any case having to wrap the `file='path/to/file.svg'` in require seems clunky.

**Comment by natew** [comment]
It may seem clunky but it has a big upside which is that it allows us to do inline icons. Inline is necessary for mobile because otherwise you will see delay while the icon loads externally unless you do clever optimizations. Inline also is the only way you can control the color of an svg fill, external icons you can't change with CSS.

We could add another dynamic require as an option but it would be more code and add another warning to the webpack build like the routes warning currently. I'll leave this open for now, but I like the require as it is explicit, and also performant.

**Comment by mbrookes** [comment]
Ah that makes sense. If there was a way to surpress the webpack warnings then a dynamic require would be ideal, but if that's not possible, then consider this a docs issue request. :wink:

**Comment by natew** [comment]
Updated docs today :)
