### ISSUE TITLE
View title and BackButton text don't align during transition.

### ISSUE THREAD

**Issue by mbrookes** [reapp/reapp-ui#49]
This is a look-and-feel issue compared to native. Not sure if this sort of feedback is helpful, so feel free to close if this is already as good as it can be in the current implementation.

In native iOS apps, the text of the back-button is the same string as the title of the previous page. The transition is that the title of the first page slides over to become the back button of the sub-page, whilst also fading color between the title and button color (black to blue in this case) via a lighter shade.

![screen shot 2015-04-10 at 22 26 09](https://cloud.githubusercontent.com/assets/357702/7097757/8d9cc0ce-dfd0-11e4-8c66-a169b33ecf0d.png)

In this example the 'Mailboxes' title is sliding left to become the back button text, while the new title 'Junk' slides (and fades) in from the right.

In reapp, the View title and Back Button text don't align during the transition:

![screen shot 2015-04-10 at 22 23 03](https://cloud.githubusercontent.com/assets/357702/7097719/37833f7e-dfd0-11e4-9de2-ad6f7be70c8a.png)

Ignore the ugly buttons on the Home view - it's a WIP! (It would be good if the template app used a list by default though.)

A couple of related-ish issues:
- In native, the selected list item fades darker, and stays faded as the new view overlaps. It only fades up when returning to the original view. In reapp the list item flashes when tapped, but doesn't hold it's state.
- When sliding the view from the left, if it is held and dragged, the animation is very janky (is that a technical term? :smile ). [Edit: no it isn't - `use reapp run -e production` for better performance)
- When sliding with momentum, the movement is much slower compared to a native app that has been given the same speed of "swipe". Even a slow swipe to the point of only just passing the snap-back speed still moves quite quickly in native.

**Comment by natew** [comment]
@mbrookes these are all things on my personal list for things to clean up in Reapp. In fact theres one ticket here for dynamic speed of scroll animations that has to do with your third point.

There is a big update I'm planning on starting in a week. It's going to have a new way of managing Views that is just like native (and is even inspired by react native's handling). Right now you can have a ViewList with Views, and you manage those yourself. If you use our router, we give you helpers too.

But on native you can infinitely nest Views just by pushing them onto a stack. This is easily doable with ViewList as the underlying implementation. We'd implement it as `<Navigator />` and you'd do stuff like navigator.push(nextView)`. And then, we could also have access to the Title attributes and automatically set those (if the user wanted that).

See here for how it's done in Native: https://github.com/reapp/reapp-kit-demo/blob/master/index.js

This would be a really awesome change and would be trivial to transition old apps over to.

This is also nice because it means users can manage their own stacks of views. You could easily then have a different stack for each TabBar.Item and have them keep there stack when you toggle to/from the tab.

That said, the alignment of text isn't perfect right now either in ViewLists as seen in your screenshot. It's a tricky problem because it's a different type of animation. Rather than saying how you want to animate (move left at this rate) you need to say where to animate it (move to this position). It's doable within the current animation framework, but again requires a little work to get done.

**Comment by natew** [comment]
Another thing that needs work is to adjust the animation fade-out/in to be a little less linear. Right now they just fade out and in linearly, but what we want is for the old text to fade out earlier in the animation and then the new text fade in later, as you can see in your mail screenshot. That would be the easiest change for now and would even help with the overlapping text ugliness we see now.

Would love help on any of this! I've got a ton on my plate, but once I finish this client project my next steps are to do the Navigator changes, then refactor the data management stuff into it's own module, and finally document and release reapp-kit better for launch.

**Comment by mbrookes** [comment]
This is probably a naive question, but particularly with the view stack idea, if the back button is automatically set to the previous title (or in the current implementation if the user sets them the both same), could you not just use one element for both the title and back button text, and just animate it between positions? 

If the title and back button aren't the same text, it really doesn't matter much if the animations don't overlap perfectly, as the text isn't going to match anyway.

I'm really enjoying getting my head around reapp and learning a ton in the process, so if when I feel a bit more confident I can contribute something without getting in the way, I'd be glad to pitch in. As it stands, capturing these sorts of issues or where I found things difficult to understand is probably the best I can offer.

I do think once things are a bit more stable and better documented you'll get more qualified parties able to help out. Look at the attentionTouchstone has recieved, and it hasn't even launched yet!

**Comment by natew** [comment]
Yea I think that's a good idea. Things are early on for reapp. As for your question... ViewLists are by far the most complex piece of Reapp. They have lots of requirements, state, animations, etc.

In short, yes we do need two different elements. It's hard to even know how to explain fully why because it would take a while (basically a <View /> must stand alone outside view lists), but my feeling is it's actually a much cleaner and more accurate implementation the way it is (I think), it just will be harder to get the animation right.

If you check out the iOS Messages app you'll see what I mean as well. They don't sync perfectly.

Reasons why? I think because not always do you want matching titles, that's actually a special case. Though I'm not an expert here.

**Comment by mbrookes** [comment]
I looked at messages, and the only view list transition I could see is the "Messages" title to back button transition, which doesn't have any issues - to me it looks like a single object being animated, but one overlaid on the other with the same start and end position, and same animation would be indistingushable.

To be fair this whole thing is a minor detail, and not noticable for a fast swipe. The manual swipe (where this is more obvious) is so janky at the moment as to be unusable (on an iPhone 5S at least), so that's clearly the priority. :wink:

**Comment by natew** [comment]
Yea there's some jank that we actually made worse recently. Also notice if you're running in dev it's much much slower.

I have a branch I'm working on a few optimizations.

**Comment by mbrookes** [comment]
Ah, sorry, I hadn't realised that - I just tried production and the difference is phenominal! I completely take back my previous comment! :smile:

Actually, that was one of my (unsubmitted) docs questions. It does say in the getting started guide that it's quicker, but it doesn't say what's quicker or why. A one-liner in the docs to explain the difference would be good. :ok_hand:

**Comment by natew** [comment]
Nice! Glad to hear. There is still jank that creeps in. If your phone is running slow, or if you have a complex page. I know I can make a few things quicker still :)

**Comment by natew** [comment]
Will add that to docs better.

**Comment by mbrookes** [comment]
Might also be worth having a note up near the installation steps at the top of Get Started to use: `reapp run -e production` if testing reapp on a mobile device, otherwise someone just giving it a quick spin could be turned off by the development mode's apparent performance.

**Comment by natew** [comment]
@mbrookes Will do. Also, released an update for viewlists today. It increases performance and also applies the fade effect so they don't overlap so much. They are still offset, but when I get time I can tweak that now as well and they should be near pixel-perfect.
