### ISSUE TITLE
Views don't update during animations, is there a way to override this?

### ISSUE THREAD

**Issue by clauderic** [reapp/reapp-ui#68]
By default, Views in NestedViewList don't update until animations have completed. Is there a way to override this or force it to call the render method once before animating?

**Comment by ryd0rz** [comment]
@clauderic - If you change state on a component it will render. You could try setting a state variable for "render" within the component to false in the initialState, and then set it to true before you begin the animation, so that it forces a render on the component. To set it back, you can then use willReceiveProps to update it to false again.
